openapi: 3.0.2
info:
  title: Product Management
  description: |
    Specifications of the legacy homegrown product management microservice
  contact:
    name: Alan Belisle
    email: abelisle@salesforce.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
- name: products
  description: Operations about products
paths:
  /products:
    post:
      tags:
      - products
      summary: Create products
      operationId: createProducts
      requestBody:
        description: Products to create
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Product'
      responses:
        "201":
          description: Products created successfully
components:
  schemas:
    Product:
      required:
      - companyName
      type: object
      properties:
        productId:
          type: string
          description: Unique identifier for each product
        productName:
          type: string
          description: Name or short description of the product
        isActive:
          type: boolean
          description: |
            Indicates if the product is active (e.g., current product) or inactive
            (e.g., retired product)
        createdAt:
          type: string
          description: Timestamp for when the product record was created
          format: date-time
        updatedAt:
          type: string
          description: Timestamp for when the record was last updated
          format: date-time
