# Spring Boot Application Properties
server:
  # address:  0.0.0.0
  # Default port is 8080
  port: 8081
  error:
    include-message: always
  servlet:
    # Default context-path is /
    context-path: /api
